# Generated by Django 3.0.6 on 2020-05-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('show', models.BooleanField()),
                ('alt_text', models.CharField(blank=True, max_length=15)),
                ('img_class', models.CharField(max_length=40)),
            ],
        ),
    ]
